---
{{- if .Values.elasticsearch_hpa.hpa_enabled }}
apiVersion: autoscaling.k8s.elastic.co/v1alpha1
kind: ElasticsearchAutoscaler
metadata:
  name: {{- .Values.elasticsearch.name }}-autoscaling
spec:
  elasticsearchRef:
    name: {{- .Values.elasticsearch.name }}
  policies:
    {{- if .Values.elasticsearch_hpa.data_hot_hpa_enabled }}
    - name: data-hot
      roles: {{- .Values.elasticsearch.nodeSets.master.config.node.roles }}
      resources:
        nodeCount:
          min: {{- .Values.elasticsearch_hpa.node_count_min }}
          max: {{- .Values.elasticsearch_hpa.node_count_max }}
        cpu:
          min: {{- .Values.elasticsearch_hpa.cpu_min }}
          max: {{- .Values.elasticsearch_hpa.cpu_max }}
        memory:
          min: {{- .Values.elasticsearch_hpa.mem_min }}
          max: {{- .Values.elasticsearch_hpa.mem_max }}
        storage:
          min: {{- .Values.elasticsearch_hpa.storage_min }}
          max: {{- .Values.elasticsearch_hpa.storage_max }}
    {{- end }}
{{- end }}