apiVersion: autoscaling.k8s.elastic.co/v1alpha1
kind: ElasticsearchAutoscaler
metadata:
  name: prod-es-cluster-autoscaling
spec:
  elasticsearchRef:
    name: prod-es-cluster
  policies:
    - name: data-hot
      roles: ["data_hot", "data_content" , "ingest"]
      resources:
        nodeCount:
          min: 1
          max: 3
        cpu:
          min: 1
          max: 2
        memory:
          min: 2Gi
          max: 2Gi
        storage:
          min: 50Gi
          max: 100Gi