---
{{- if .Values.kibana.enabled }}
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: ${{ .Values.kibana.name }}
spec:
  version: ${{ .Values.kibana.version }}
  count: ${{ .Values.kibana.count }}
  {{- if not ( .Values.kibana.enableHttpTLS | default true ) }}
  elasticsearchRef:
    name: ${{ .Values.elasticsearch.name }}-cluster
  {{- else }}
  config:
    {{- include "elasticsearch-cluster.kibanaConfig" () | nindent 4 }}
  {{- end }}
  http:
    service:
      spec:
        type: ${{ .Values.kibana.service_type }}
  podTemplate:
    spec:
      {{- if and ( .Values.kibana.enableHttpTLS | default true ) ( .Values.kibana.enableIngressTLS | default true ) }}
      volumes:
      {{- include "elasticsearch-cluster.kibanaExtraVolumes" () | nindent 6 }}
      {{- end }}
      containers:
      - name: kibana
        {{- if and ( .Values.kibana.enableHttpTLS | default true ) ( .Values.kibana.enableIngressTLS | default true ) }}
        volumeMounts:
        {{- include "elasticsearch-cluster.kibanaExtraVolumeMounts" () | nindent 8 }}
        {{- end }}
        resources:
          limits:
            memory: ${{ .Values.kibana.kibana_mem_limit }}
            cpu: ${{ .Values.kibana.kibana_cpu_limit }}
          requests:
            memory: ${{ .Values.kibana.kibana_mem_request }}
            cpu: ${{ .Values.kibana.kibana_cpu_request }}
{{- end }}
---
{{- if .Values.kibana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ .Values.kibana.name }}-ingress
  annotations:
    networking.gke.io/managed-certificates: kibana
    kubernetes.io/ingress.class: ${{ .Values.kibana.ingress.className }}
    {{- if .Values.kibana.ingress.use_externaldns }}
    external-dns.alpha.kubernetes.io/hostname: kibana.${{ .Values.kibana.ingress.root_domain }}
    {{- end }}
spec:
  {{- if .Values.kibana.enableIngressTLS | default true }}
  tls:
  - hosts:
      - kibana.${{ .Values.kibana.ingress.root_domain }}
    secretName: {{ .Values.kibana.cert_name }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: ${{ .Values.kibana.ingress.path }}
        pathType: ${{ .Values.kibana.ingress.path_type }}
        backend:
          service:
            name: ${{ .Values.kibana.name }}-kb-http
            port:
              number: ${{ .Values.kibana.ingress.port }}
{{- end }}