---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: prod-kibana
spec:
  version: 8.15.3
  count: 1
  elasticsearchRef:
    name: prod-es-cluster
  http:
    service:
      spec:
        type: ClusterIP
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
            cpu: "250Mi"
          requests:
            memory: 1Gi
            cpu: "250Mi"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    external-dns.alpha.kubernetes.io/hostname: kibana.normanguys.dev # need to be parameterized
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-kibana-kb-http
            port:
              number: 5601